export const progressStyle = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize:30,
  separatorStrokeWidth: 1,
  currentStepStrokeWidth: 1,
  stepStrokeCurrentColor: '#048FC1',
  stepStrokeWidth: 1,
  stepStrokeFinishedColor: '#048FC1',
  stepStrokeUnFinishedColor: '#aaaaaa',
  separatorFinishedColor: '#048FC1',
  separatorUnFinishedColor: '#aaaaaa',
  stepIndicatorFinishedColor: '#048FC1',
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 10,
  currentStepIndicatorLabelFontSize: 10,
  stepIndicatorLabelCurrentColor: '#048FC1',
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: '#aaaaaa',
  labelColor: '#999999',
  labelSize: 12,
  labelAlign: 'flex-end',
  currentStepLabelColor: '#048FC1'
}
